USE quant_ops;

CREATE TABLE IF NOT EXISTS schema_migrations (
    migration_id VARCHAR(64) PRIMARY KEY,
    applied_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET @beijing_time_migrated = (
    SELECT COUNT(*) FROM schema_migrations WHERE migration_id = '007_beijing_time'
);

-- Changing TIMESTAMP columns can touch ON UPDATE values. Preserve them before
-- altering the column types, then restore the exact original wall-clock time.
DROP TEMPORARY TABLE IF EXISTS pipeline_time_backup;
CREATE TEMPORARY TABLE pipeline_time_backup AS
SELECT pipeline_id, created_at, updated_at FROM pipelines;

DROP TEMPORARY TABLE IF EXISTS task_time_backup;
CREATE TEMPORARY TABLE task_time_backup AS
SELECT task_id, created_at, updated_at FROM tasks;

-- Store wall-clock Beijing time consistently. DATETIME avoids implicit
-- TIMESTAMP conversion when a client has an unexpected session time zone.
ALTER TABLE agents
    MODIFY last_heartbeat DATETIME NULL,
    MODIFY created_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tasks
    MODIFY created_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFY updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE task_instances
    MODIFY start_time DATETIME NULL,
    MODIFY end_time DATETIME NULL;
ALTER TABLE trade_calendar
    MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE pipelines
    MODIFY created_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFY updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

UPDATE pipelines AS p
JOIN pipeline_time_backup AS b ON b.pipeline_id = p.pipeline_id
SET p.created_at = b.created_at, p.updated_at = b.updated_at;

UPDATE tasks AS t
JOIN task_time_backup AS b ON b.task_id = t.task_id
SET t.created_at = b.created_at, t.updated_at = b.updated_at;

-- Existing values produced by MySQL NOW()/CURRENT_TIMESTAMP while the server
-- used UTC need a one-time +08:00 correction. Values written by Manager with
-- to_cst_time_str were already Beijing time and are intentionally preserved.
UPDATE agents
SET last_heartbeat = IF(last_heartbeat IS NULL, NULL, DATE_ADD(last_heartbeat, INTERVAL 8 HOUR)),
    created_at = IF(created_at IS NULL, NULL, DATE_ADD(created_at, INTERVAL 8 HOUR))
WHERE @beijing_time_migrated = 0;

UPDATE tasks
SET created_at = IF(created_at IS NULL, NULL, DATE_ADD(created_at, INTERVAL 8 HOUR)),
    updated_at = IF(updated_at IS NULL, NULL, DATE_ADD(updated_at, INTERVAL 8 HOUR))
WHERE @beijing_time_migrated = 0;

UPDATE trade_calendar
SET created_at = DATE_ADD(created_at, INTERVAL 8 HOUR)
WHERE @beijing_time_migrated = 0;

UPDATE users
SET last_login_at = IF(last_login_at IS NULL, NULL, DATE_ADD(last_login_at, INTERVAL 8 HOUR)),
    created_at = DATE_ADD(created_at, INTERVAL 8 HOUR)
WHERE @beijing_time_migrated = 0;

UPDATE ddb_monitor_group
SET created_at = DATE_ADD(created_at, INTERVAL 8 HOUR),
    updated_at = DATE_ADD(updated_at, INTERVAL 8 HOUR)
WHERE @beijing_time_migrated = 0;

UPDATE ddb_monitor
SET created_at = DATE_ADD(created_at, INTERVAL 8 HOUR),
    updated_at = DATE_ADD(updated_at, INTERVAL 8 HOUR)
WHERE @beijing_time_migrated = 0;

UPDATE ddb_monitor_snapshot
SET checked_at = IF(checked_at IS NULL, NULL, DATE_ADD(checked_at, INTERVAL 8 HOUR))
WHERE @beijing_time_migrated = 0;

-- These seeded values were generated by UTC defaults. Other Pipeline values
-- were supplied explicitly by Manager in Beijing time.
UPDATE pipelines
SET created_at = DATE_ADD(created_at, INTERVAL 8 HOUR)
WHERE @beijing_time_migrated = 0
  AND pipeline_id IN ('test_pipeline_alpha', 'test_pipeline_beta');

UPDATE pipelines
SET updated_at = DATE_ADD(updated_at, INTERVAL 8 HOUR)
WHERE @beijing_time_migrated = 0
  AND pipeline_id = 'main_daily_dag';

INSERT IGNORE INTO schema_migrations(migration_id, applied_at)
VALUES ('007_beijing_time', DATE_ADD(UTC_TIMESTAMP(), INTERVAL 8 HOUR));

SET GLOBAL time_zone = '+08:00';
SET time_zone = '+08:00';

DROP TEMPORARY TABLE pipeline_time_backup;
DROP TEMPORARY TABLE task_time_backup;
