import type { DagGraph } from '../types.js'

export const dagGraphs: DagGraph[] = [
  {
    id: 'daily-factor-pipeline',
    name: '每日因子流水线',
    description: '行情、财务、基础信息到多因子生成与风控校验的主流程',
    canvas: { width: 1100, height: 560 },
    nodes: [
      {
        id: 'task_market_stock_daily',
        name: '股票行情',
        status: 'success',
        x: 40,
        y: 210,
        latestExecId: 'task_market_stock_daily_1782303300',
        agent: 'node_001',
        duration: '18m 22s',
      },
      {
        id: 'task_basic_financial_daily',
        name: '财务数据',
        status: 'success',
        x: 230,
        y: 120,
        latestExecId: 'task_basic_financial_daily_dag_1782304401',
        agent: 'node_001',
        duration: '12m 08s',
      },
      {
        id: 'task_derived_metrics_daily',
        name: '衍生指标',
        status: 'success',
        x: 420,
        y: 120,
        latestExecId: 'task_derived_metrics_daily_dag_1782305120',
        agent: 'node_001',
        duration: '9m 41s',
      },
      {
        id: 'task_stock_info_daily',
        name: '股票信息',
        status: 'running',
        x: 230,
        y: 300,
        latestExecId: 'task_stock_info_daily_dag_1782305902',
        agent: 'node_001',
        duration: '运行中',
      },
      {
        id: 'task_cj_quant_factors_daily',
        name: 'CJ 因子',
        status: 'waiting',
        x: 420,
        y: 240,
        latestExecId: '待触发',
        agent: 'windows-worker-01',
        duration: '-',
      },
      {
        id: 'task_fz_quant_factors_daily',
        name: 'FZ 因子',
        status: 'waiting',
        x: 610,
        y: 240,
        latestExecId: '待触发',
        agent: 'node_001',
        duration: '-',
      },
      {
        id: 'task_research_factors_daily',
        name: '投研因子',
        status: 'waiting',
        x: 800,
        y: 180,
        latestExecId: '待触发',
        agent: 'node_001',
        duration: '-',
      },
      {
        id: 'task_risk_check_daily',
        name: '风控校验',
        status: 'waiting',
        x: 800,
        y: 330,
        latestExecId: '待触发',
        agent: 'node_001',
        duration: '-',
      },
    ],
    edges: [
      { from: 'task_market_stock_daily', to: 'task_basic_financial_daily' },
      { from: 'task_basic_financial_daily', to: 'task_derived_metrics_daily' },
      { from: 'task_market_stock_daily', to: 'task_stock_info_daily' },
      { from: 'task_stock_info_daily', to: 'task_cj_quant_factors_daily' },
      { from: 'task_cj_quant_factors_daily', to: 'task_fz_quant_factors_daily' },
      { from: 'task_derived_metrics_daily', to: 'task_research_factors_daily' },
      { from: 'task_fz_quant_factors_daily', to: 'task_research_factors_daily' },
      { from: 'task_stock_info_daily', to: 'task_risk_check_daily' },
    ],
  },
  {
    id: 'pre-market-risk-check',
    name: '盘前风控检查',
    description: '交易日前置数据校验、账户同步、风控规则检查与交易许可发布',
    canvas: { width: 980, height: 520 },
    nodes: [
      {
        id: 'task_sync_account_snapshot',
        name: '账户快照',
        status: 'success',
        x: 40,
        y: 220,
        latestExecId: 'task_sync_account_snapshot_1782310100',
        agent: 'node_001',
        duration: '2m 16s',
      },
      {
        id: 'task_load_position',
        name: '持仓同步',
        status: 'success',
        x: 240,
        y: 120,
        latestExecId: 'task_load_position_1782310240',
        agent: 'node_001',
        duration: '3m 02s',
      },
      {
        id: 'task_load_cash',
        name: '资金同步',
        status: 'success',
        x: 240,
        y: 310,
        latestExecId: 'task_load_cash_1782310308',
        agent: 'node_001',
        duration: '1m 44s',
      },
      {
        id: 'task_check_limits',
        name: '限额检查',
        status: 'running',
        x: 460,
        y: 220,
        latestExecId: 'task_check_limits_1782310450',
        agent: 'risk-worker-02',
        duration: '运行中',
      },
      {
        id: 'task_publish_trade_permission',
        name: '交易许可',
        status: 'waiting',
        x: 700,
        y: 220,
        latestExecId: '待触发',
        agent: 'risk-worker-02',
        duration: '-',
      },
    ],
    edges: [
      { from: 'task_sync_account_snapshot', to: 'task_load_position' },
      { from: 'task_sync_account_snapshot', to: 'task_load_cash' },
      { from: 'task_load_position', to: 'task_check_limits' },
      { from: 'task_load_cash', to: 'task_check_limits' },
      { from: 'task_check_limits', to: 'task_publish_trade_permission' },
    ],
  },
  {
    id: 'intraday-monitoring',
    name: '盘中监控告警',
    description: '行情订阅、成交回报、异常检测和告警通知的盘中监控链路',
    canvas: { width: 1180, height: 560 },
    nodes: [
      {
        id: 'task_stream_market_ticks',
        name: '行情订阅',
        status: 'running',
        x: 40,
        y: 180,
        latestExecId: 'task_stream_market_ticks_1782312200',
        agent: 'windows-worker-01',
        duration: '运行中',
      },
      {
        id: 'task_stream_trade_events',
        name: '成交回报',
        status: 'running',
        x: 40,
        y: 330,
        latestExecId: 'task_stream_trade_events_1782312201',
        agent: 'node_002',
        duration: '运行中',
      },
      {
        id: 'task_merge_realtime_state',
        name: '实时状态聚合',
        status: 'running',
        x: 280,
        y: 250,
        latestExecId: 'task_merge_realtime_state_1782312300',
        agent: 'node_002',
        duration: '运行中',
      },
      {
        id: 'task_detect_price_anomaly',
        name: '价格异常检测',
        status: 'success',
        x: 520,
        y: 150,
        latestExecId: 'task_detect_price_anomaly_1782312420',
        agent: 'alert-worker-01',
        duration: '42s',
      },
      {
        id: 'task_detect_trade_anomaly',
        name: '交易异常检测',
        status: 'failed',
        x: 520,
        y: 350,
        latestExecId: 'task_detect_trade_anomaly_1782312425',
        agent: 'alert-worker-01',
        duration: '失败',
      },
      {
        id: 'task_notify_ops_channel',
        name: '运维通知',
        status: 'waiting',
        x: 780,
        y: 250,
        latestExecId: '待触发',
        agent: 'notify-worker-01',
        duration: '-',
      },
      {
        id: 'task_archive_intraday_logs',
        name: '日志归档',
        status: 'waiting',
        x: 980,
        y: 250,
        latestExecId: '待触发',
        agent: 'node_002',
        duration: '-',
      },
    ],
    edges: [
      { from: 'task_stream_market_ticks', to: 'task_merge_realtime_state' },
      { from: 'task_stream_trade_events', to: 'task_merge_realtime_state' },
      { from: 'task_merge_realtime_state', to: 'task_detect_price_anomaly' },
      { from: 'task_merge_realtime_state', to: 'task_detect_trade_anomaly' },
      { from: 'task_detect_price_anomaly', to: 'task_notify_ops_channel' },
      { from: 'task_detect_trade_anomaly', to: 'task_notify_ops_channel' },
      { from: 'task_notify_ops_channel', to: 'task_archive_intraday_logs' },
    ],
  },
]
